### Create job
POST http://localhost:3000/api/processing/start
Content-Type: application/json

{
  "totalRecords": 150,
  "recordsPerMinute": 100
}


### Update job config
PATCH http://localhost:3000/api/processing/8a8a51ef-3e40-4d49-b6dd-e29efe354d6e/config
Content-Type: application/json

{
  "recordsPerMinute": 500
}

### Check job status (completed job)
GET http://localhost:3000/api/processing/33324937-0c3f-434f-90ab-9396fe2882cd/status

### Check job status (processing job)
GET http://localhost:3000/api/processing/54e9afe6-66b0-4866-873d-d82fe84767a3/status

### Check job status (non-existent job)
GET http://localhost:3000/api/processing/non-existent-job-id/status