### Create job
POST http://localhost:3000/api/processing/start
Content-Type: application/json

{
  "totalRecords": 100,
  "totalMinutes": 200
}


### Update job config
PATCH http://localhost:3000/api/processing/611d3e41-619a-482a-9f20-a8d3fb9955e2/config
Content-Type: application/json

{
  "totalMinutes": 500
}

### Check job status (completed job)
GET http://localhost:3000/api/processing/54e9afe6-66b0-4866-873d-d82fe84767a3/status

### Check job status (processing job)
GET http://localhost:3000/api/processing/54e9afe6-66b0-4866-873d-d82fe84767a3/status

### Check job status (non-existent job)
GET http://localhost:3000/api/processing/non-existent-job-id/status